spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Samir121416
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}